### PR TITLE
[WIP] Start conversion to serde

### LINKED ISSUE #9: Move to Serde
rustc-serialize is now deprecated in favour of Serde, which hit 1.0

### PR DESCRIPTION
**Pull request by torkleyy**
Fixes #9 

Only serializer is implemented so far

### CODE REVIEW

**Comment by torkleyy** [comment]
Serde handles (sized) arrays the same as tuples. But I think ron has different syntax for those, right?

**Comment by kvark** [comment]
> Serde handles (sized) arrays the same as tuples. But I think ron has different syntax for those, right?

RON doesn't use fixed-size arrays, so this limitation seems fine

**Comment by torkleyy** [comment]
But the problem is that `&[i32]` serializes to `[3, 4]` but `&[i32; 2]` to `(3, 4)`.

**Comment by torkleyy** [comment]
Unfortunately, I won't be able to do the deserialization today. More precisely, not until Friday :(

**Comment by torkleyy** [comment]
Writing a good deserializer by hand is annoying... @Xaeroxe you asked if there's anything you could help out with, got an idea how to implement it properly?

**Comment by kvark** [comment]
@torkleyy We need a parser, be it either Peg/Nom/something else. I'd prefer something with less macros, all other conditions being equal.

**Comment by torkleyy** [comment]
Do you have anything against LALRPOP? https://github.com/nikomatsakis/lalrpop

**Comment by kvark** [comment]
@torkleyy I haven't looked at it, to be honest. The fact that Nico is behind it inspires confidence, but I'm somewhat surprised that the root doesn't have an examples folder to get a better idea.

**Comment by torkleyy** [comment]
There is a link to a tutorial which contains example code.

**Comment by torkleyy** [comment]
I'm not sure if we really need LALRPOP or if it is even of any use. The JSON implementation for serde does not use one as far as I can see it.

**Comment by kvark** [comment]
:shipit:

**Pull request merged**
